apiVersion: golearning.dev/v1alpha1
kind: Kluster
metadata:
  name: kluster-1
spec:
  name: kluster-1
  region: "blr1"
  version: "1.22.13-do.0"
  tokenSecret: "default/dosecret"
  nodePools:
    - count: 1
      name: "dummy-nodepool"
      size: "s-1vcpu-2gb"
